-- MySQL Script generated by MySQL Workbench
-- sáb 22 may 2021 12:01:56
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering
-- create database granja;
-- use granja;	
-- -----------------------------------------------------
-- Table `granjas`
-- -----------------------------------------------------
CREATE TABLE `granjas` (
  `idGranja` INT NOT NULL AUTO_INCREMENT,
  `nombreGranja` VARCHAR(30) NOT NULL,
  `ubicacion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idGranja`))
ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `galpones`
-- -----------------------------------------------------
CREATE TABLE `galpones` (
  `idGalpon` INT NOT NULL AUTO_INCREMENT,
  `idGranja` INT NOT NULL,
  `numeroGalpon` INT NOT NULL,
  `fechaA` DATE NOT NULL,
  `activo` TINYINT(1) NOT NULL DEFAULT 1,
  `areaUtil` FLOAT NOT NULL,
  `confinamiento` CHAR NOT NULL,
  PRIMARY KEY (`idGalpon`),
  CONSTRAINT `fk_galpones_granjas1`
    FOREIGN KEY (`idGranja`)
    REFERENCES `granjas` (`idGranja`)
    ON DELETE CASCADE 
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table `lineagenetica`
-- -----------------------------------------------------
CREATE TABLE `lineagenetica` (
  `idLineaGenetica` INT NOT NULL AUTO_INCREMENT,
  `nombreLienaGenetica` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`idLineaGenetica`))
ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `lotes`
-- -----------------------------------------------------
CREATE TABLE `lotes` (
  `idlote` INT NOT NULL AUTO_INCREMENT,
  `idLineaGenetica` INT NOT NULL,
  `numeroGallinas` INT NOT NULL,
  PRIMARY KEY (`idlote`),
  CONSTRAINT `fk_lotes_lineagenetica1`
    FOREIGN KEY (`idLineaGenetica`)
    REFERENCES `lineagenetica` (`idLineaGenetica`)
     ON DELETE CASCADE 
    ON UPDATE CASCADE)
ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `datosgallina`
-- -----------------------------------------------------
CREATE TABLE `datosgallina` (
  `idDatoGallina` INT NOT NULL AUTO_INCREMENT,
  `nombreItem` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idDatoGallina`))
ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `detallegenetica`
-- -----------------------------------------------------
CREATE TABLE `detallegenetica` (
  `idDatosGallina` INT NOT NULL,
  `idLineaGenetica` INT NOT NULL,
  `valor` FLOAT NOT NULL,
  `semana` INT NOT NULL,
  PRIMARY KEY (`idDatosGallina`, `idLineaGenetica`),
  CONSTRAINT `fk_detallegenetica_itemdetallegenetica`
    FOREIGN KEY (`idDatosGallina`)
    REFERENCES `datosgallina` (`idDatoGallina`)
     ON DELETE CASCADE 
    ON UPDATE CASCADE,
  CONSTRAINT `fk_detallegenetica_lineagenetica1`
    FOREIGN KEY (`idLineaGenetica`)
    REFERENCES `lineagenetica` (`idLineaGenetica`)
     ON DELETE CASCADE 
    ON UPDATE CASCADE)
ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `galponeslotes`
-- -----------------------------------------------------
CREATE TABLE `galponeslotes` (
  `idGalpon` INT NOT NULL,
  `idlote` INT NOT NULL,
  `activo` TINYINT NOT NULL DEFAULT 1,
  `fechaInicio` DATE NOT NULL,
  `fechaFin` DATE NULL,
  `numeroLote` INT NOT NULL,
  PRIMARY KEY (`idGalpon`, `idlote`),
  CONSTRAINT `fk_galpones_has_lotes_galpones1`
    FOREIGN KEY (`idGalpon`)
    REFERENCES `galpones` (`idGalpon`)
     ON DELETE CASCADE 
    ON UPDATE CASCADE,
  CONSTRAINT `fk_galpones_has_lotes_lotes1`
    FOREIGN KEY (`idlote`)
    REFERENCES `lotes` (`idlote`)
     ON DELETE CASCADE 
    ON UPDATE CASCADE)
ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `tipopersona`
-- -----------------------------------------------------
CREATE TABLE `tipopersona` (
  `idTipoPersona` INT NOT NULL AUTO_INCREMENT,
  `nombreTipoPersona` BLOB NOT NULL,
  `descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`idTipoPersona`))
ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `personas`
-- -----------------------------------------------------
CREATE TABLE `personas` (
  `documento` VARCHAR(11) NOT NULL,
  `nombresPersona` VARCHAR(45) NOT NULL,
  `apellidosPersona` VARCHAR(45) NULL,
  `telefono` VARCHAR(11) NOT NULL,
  `email` VARCHAR(45) NULL,
  `activo` VARCHAR(45) NULL,
  `idTipoPersona` INT NOT NULL,
  PRIMARY KEY (`documento`),
  CONSTRAINT `fk_personas_tipopersona1`
    FOREIGN KEY (`idTipoPersona`)
    REFERENCES `tipopersona` (`idTipoPersona`)
     ON DELETE CASCADE 
    ON UPDATE CASCADE)
ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `galponeroslotes`
-- -----------------------------------------------------
CREATE TABLE `galponeroslotes` (
  `idGalpon` INT NOT NULL,
  `idlote` INT NOT NULL,
  `documento` VARCHAR(11) NOT NULL,
  PRIMARY KEY (`idGalpon`, `idlote`, `documento`),
  CONSTRAINT `fk_galponeslotes_has_galponeros_galponeslotes1`
    FOREIGN KEY (`idGalpon` , `idlote`)
    REFERENCES `galponeslotes` (`idGalpon` , `idlote`)
     ON DELETE CASCADE 
    ON UPDATE CASCADE,
  CONSTRAINT `fk_galponeroslotes_personas1`
    FOREIGN KEY (`documento`)
    REFERENCES `personas` (`documento`)
     ON DELETE CASCADE 
    ON UPDATE CASCADE)
ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `informacionlote`
-- -----------------------------------------------------
CREATE TABLE `informacionlote` (
  `fecha` DATE NOT NULL,
  `idGalpon` INT NOT NULL,
  `idlote` INT NOT NULL,
  `idDatoGallina` INT NOT NULL,
  `valor` INT NOT NULL,
  PRIMARY KEY (`fecha`, `idGalpon`, `idlote`, `idDatoGallina`),
  CONSTRAINT `fk_datosgallina_has_lotes_datosgallina1`
    FOREIGN KEY (`idDatoGallina`)
    REFERENCES `datosgallina` (`idDatoGallina`)
     ON DELETE CASCADE 
    ON UPDATE CASCADE,
  CONSTRAINT `fk_informacionlote_galponeslotes1`
    FOREIGN KEY (`idGalpon` , `idlote`)
    REFERENCES `galponeslotes` (`idGalpon` , `idlote`)
     ON DELETE CASCADE 
    ON UPDATE CASCADE)
ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `tipoproducto`
-- -----------------------------------------------------
CREATE TABLE `tipoproducto` (
  `idTipoProducto` INT NOT NULL AUTO_INCREMENT,
  `nombreTipoProducto` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTipoProducto`))
ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `productos`
-- -----------------------------------------------------
CREATE TABLE `productos` (
  `idProducto` INT NOT NULL AUTO_INCREMENT,
  `nombreProducto` VARCHAR(45) NOT NULL,
  `idTipoProducto` INT NOT NULL,
  PRIMARY KEY (`idProducto`),
  CONSTRAINT `fk_productos_tipoproducto1`
    FOREIGN KEY (`idTipoProducto`)
    REFERENCES `tipoproducto` (`idTipoProducto`)
     ON DELETE CASCADE 
    ON UPDATE CASCADE)
ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `recogidas`
-- -----------------------------------------------------
CREATE TABLE `recogidas` (
  `idRecogida` INT NOT NULL AUTO_INCREMENT,
  `fechaRecogida` DATE NOT NULL,
  `idGalpon` INT NOT NULL,
  `idlote` INT NOT NULL,
  PRIMARY KEY (`idRecogida`),
  CONSTRAINT `fk_registros_galponeslotes1`
    FOREIGN KEY (`idGalpon` , `idlote`)
    REFERENCES `galponeslotes` (`idGalpon` , `idlote`)
     ON DELETE CASCADE 
    ON UPDATE CASCADE)
ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `tipohuevo`
-- -----------------------------------------------------
CREATE TABLE `tipohuevo` (
  `idTipoHuevo` INT NOT NULL AUTO_INCREMENT,
  `nombreTipoHuevo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTipoHuevo`))
ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `valores`
-- -----------------------------------------------------
CREATE TABLE `valores` (
  `idTipoHuevo` INT NOT NULL,
  `idRecogida` INT NOT NULL,
  `valor` INT NOT NULL,
  `numeroModulo` INT NOT NULL,
  PRIMARY KEY (`idTipoHuevo`, `idRecogida`),
  CONSTRAINT `fk_recogidas_has_tipohuevo_tipohuevo1`
    FOREIGN KEY (`idTipoHuevo`)
    REFERENCES `tipohuevo` (`idTipoHuevo`)
     ON DELETE CASCADE 
    ON UPDATE CASCADE,
  CONSTRAINT `fk_valores_registros1`
    FOREIGN KEY (`idRecogida`)
    REFERENCES `recogidas` (`idRecogida`)
     ON DELETE CASCADE 
    ON UPDATE CASCADE)
ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `despachos`
-- -----------------------------------------------------
CREATE TABLE `despachos` (
  `idDespacho` INT NOT NULL AUTO_INCREMENT,
  `documento` VARCHAR(11) NOT NULL,
  `precinto` VARCHAR(45) NOT NULL,
  `fechaDespacho` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idDespacho`),
  CONSTRAINT `fk_despachos_personas1`
    FOREIGN KEY (`documento`)
    REFERENCES `personas` (`documento`)
     ON DELETE CASCADE 
    ON UPDATE CASCADE)
ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `tipoventa`
-- -----------------------------------------------------
CREATE TABLE `tipoventa` (
  `idTipoVenta` INT NOT NULL AUTO_INCREMENT,
  `nombreTipoVenta` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTipoVenta`))
ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `detalledespacho`
-- -----------------------------------------------------
CREATE TABLE `detalledespacho` (
  `idTipoHuevo` INT NOT NULL,
  `idDespacho` INT NOT NULL,
  `cantidad` INT NOT NULL,
  `idTipoVenta` INT NOT NULL,
  PRIMARY KEY (`idTipoHuevo`, `idDespacho`),
  CONSTRAINT `fk_tipohuevo_has_despachos_tipohuevo1`
    FOREIGN KEY (`idTipoHuevo`)
    REFERENCES `tipohuevo` (`idTipoHuevo`)
     ON DELETE CASCADE 
    ON UPDATE CASCADE,
  CONSTRAINT `fk_tipohuevo_has_despachos_despachos1`
    FOREIGN KEY (`idDespacho`)
    REFERENCES `despachos` (`idDespacho`)
     ON DELETE CASCADE 
    ON UPDATE CASCADE,
  CONSTRAINT `fk_detalleDespacho_tipoventa1`
    FOREIGN KEY (`idTipoVenta`)
    REFERENCES `tipoventa` (`idTipoVenta`)
     ON DELETE CASCADE 
    ON UPDATE CASCADE)
ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `inventariogeneral`
-- -----------------------------------------------------
CREATE TABLE `inventariogeneral` (
  `idInventarioGeneral` INT NOT NULL AUTO_INCREMENT,
  `fechaInventario` DATE NOT NULL,
  `garantia` INT NULL,
  `documento` VARCHAR(11) NOT NULL,
  `idGranja` INT NOT NULL,
  `operacion` CHAR NOT NULL DEFAULT 'A',
  PRIMARY KEY (`idInventarioGeneral`, `idGranja`),
  CONSTRAINT `fk_inventario_personas1`
    FOREIGN KEY (`documento`)
    REFERENCES `personas` (`documento`)
     ON DELETE CASCADE 
    ON UPDATE CASCADE,
  CONSTRAINT `fk_inventariogeneral_granjas1`
    FOREIGN KEY (`idGranja`)
    REFERENCES `granjas` (`idGranja`)
     ON DELETE CASCADE 
    ON UPDATE CASCADE)
ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `detalleinventariogeneral`
-- -----------------------------------------------------
CREATE TABLE `detalleinventariogeneral` (
  `idInventario` INT NOT NULL,
  `idProducto` INT NOT NULL,
  `cantidad` INT NOT NULL,
  `precio` FLOAT NULL,
  PRIMARY KEY (`idInventario`, `idProducto`),
  CONSTRAINT `fk_detalleinventario_inventario1`
    FOREIGN KEY (`idInventario`)
    REFERENCES `inventariogeneral` (`idInventarioGeneral`)
     ON DELETE CASCADE 
    ON UPDATE CASCADE,
  CONSTRAINT `fk_detalleinventario_productos1`
    FOREIGN KEY (`idProducto`)
    REFERENCES `productos` (`idProducto`)
     ON DELETE CASCADE 
    ON UPDATE CASCADE)
ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `inventarioaves`
-- -----------------------------------------------------
CREATE TABLE `inventarioaves` (
  `idInventarioAves` INT NOT NULL AUTO_INCREMENT,
  `fechaInventario` DATE NOT NULL,
  `nuevo` INT NULL,
  `idGalpon` INT NOT NULL,
  `idlote` INT NOT NULL,
  `operacion` CHAR NOT NULL DEFAULT 'A',
  PRIMARY KEY (`idInventarioAves`),
  CONSTRAINT `fk_inventarioaves_galponeslotes1`
    FOREIGN KEY (`idGalpon` , `idlote`)
    REFERENCES `galponeslotes` (`idGalpon` , `idlote`)
     ON DELETE CASCADE 
    ON UPDATE CASCADE)
ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `detalleinventarioaves`
-- -----------------------------------------------------
CREATE TABLE `detalleinventarioaves` (
  `idProducto` INT NOT NULL,
  `idInventarioAves` INT NOT NULL,
  `cantidad` INT NOT NULL,
  `precio` FLOAT NULL,
  PRIMARY KEY (`idProducto`, `idInventarioAves`),
  CONSTRAINT `fk_detalleinventarioaves_productos1`
    FOREIGN KEY (`idProducto`)
    REFERENCES `productos` (`idProducto`)
     ON DELETE CASCADE 
    ON UPDATE CASCADE,
  CONSTRAINT `fk_detalleinventarioaves_inventarioaves1`
    FOREIGN KEY (`idInventarioAves`)
    REFERENCES `inventarioaves` (`idInventarioAves`)
     ON DELETE CASCADE 
    ON UPDATE CASCADE)
ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci;